#!/bin/bash
#
# Author: Luigi Pertoldi - pertoldi@pd.infn.it
# Created: Sun 24 Mar 2019

for d in gen/out/*; do
    runid=`basename $d`
    [ ! -f out/gerda-larmap-$runid.root ] && \
        qsub -N larmap-$runid create-larmap.qsub $runid `pwd`
done
