#!/bin/bash
#
# Author: Luigi Pertoldi - pertoldi@pd.infn.it
# Created: Sun 24 Mar 2019
#
# USAGE: qsub create-larmap.qsub <runid>
#
#$ -P short ### queue
#$ -j y     ### have logoutput and erroroutput in the same file
#$ -cwd
#$ -o /dev/null
#$ -e /dev/null

singularity exec ../bin/gerda-larmap.sif \
    create-larmap ../settings/$2 \
        "../gen/jobs/sim/$1/phmap-*.root" \
        output/gerda-larmap-$1.root &> output/create-larmap-$1.log
