#!/bin/bash
#
# Author: Luigi Pertoldi - pertoldi@pd.infn.it
# Created: Sun 24 Mar 2019
#
# USAGE: qsub map-merger.qsub <job-name> <file1.root> <file2.root> [<filen.root>]
#
#$ -P short ### queue
#$ -j y     ### have logoutput and erroroutput in the same file
#$ -cwd
#$ -o /dev/null
#$ -e /dev/null

mkdir -p merged/log
singularity exec ../bin/gerda-sw-all.simg \
    ../bin/map-merger -o merged/gerda-larmap-merged-$1.root "${@:2}" &> merged/log/map-merger-$1.log
