#!/bin/bash
#
# Author: Luigi Pertoldi - pertoldi@pd.infn.it
# Created: Sun 24 Mar 2019
#
#$ -cwd
#$ -P short
#$ -j y
#$ -o /dev/null
#$ -e /dev/null

/usr/bin/time -v singularity exec "$BASEDIR/gerda-larmap.sif" \
    /lfs/l1/gerda/gerda-simulations/gerda-larmap/bin/create-larmap "$2" \
        "$BASEDIR/gen/jobs/sim/$1/output/lar-vuv-*.root" \
        "$BASEDIR/jobs/$OUTDIR/gerda-larmap-$1.root" \
        "$3" &> "$BASEDIR/jobs/$OUTDIR/create-larmap-$1.log"
